### ISSUE TITLE
Would there be interest in a refactoring effort?

### ISSUE THREAD

**Issue by fake-name** [gprMax/gprMax#107]
Hi There!

I've been looking through the GprMax codebase in hopes of implementing a GPU solver, but I'm having trouble with a lot of the code being kind of "academic" looking.

For example, there are HUGE lines (500 characters!!!!!), lots of  extremely large functions, and just a lot of code that seems like it's just a giant ball of hair.

Would there be any interest in a series of pull requests that try to break the current ball-of-wax structure into more modular objects?

Thanks!

**Comment by agianno** [comment]
Hi Conor,

Thanks for your interest in gprMax. Indeed gprMax is an "academic" code. The GPR research group in Edinburgh that has been working on this for quite sometime - starting with a "spaghetti" code in C written by myself over the last 20 years - is made up by academics, PhD students, post-docs, etc. Although, some of us have been in computational research for a good number of years we are not professional programmers!

Any effort to make the code more robust, modular and easier to maintain and extent is very welcome although sometimes in these types of codes elegance is desirable up to the point that execution speed does not take a massive hit! 

As far as a GPU version is concerned I must say that we do have a CUDA version with very good performance that we have just finished developing for a research project. We are aiming to publish this very soon and most likely in IWAGPR 2017 and at the moment we are in discussions with our sponsors to merge this GPU gprMax branch with the main open source version of gprMax. The intention is there but things have to be done properly and approvals have to be obtained before we do this. So, if you are looking to do a CUDA implementation maybe it is a good idea to wait a little. Alternatively, an OpenCL implementation will be interesting.

Thanks again for your interest to help with gprMax!

Regards

Antonis

**Comment by fake-name** [comment]
Cool. At the moment, I'm literally just doing simple reindentation things, pep-8,  that sort of thing. Ideally, it shouldn't change the execution at all. I'l probably look at reworking the control logic into a series of more modular classes after I've done this (simple whitespace stuff like this is a great way to get a decent overview of the codebase).

I'd say I'm not a professional coder either, but then I realize that I'm somehow getting paid to do horrible things in python, so I guess I am? News to me.

If there's a CUDA implementation, I'll probably just wait. We're interested in doing a few things - CUDA/OpenCL, Variable-size sub-gridding, and being able to distribute the computation of extremely large scenes across multiple computers.

**Comment by agianno** [comment]
Great! I should mention that one of my PhD students looking into modelling GPR antennas is working on a subgrid implementation. He has done the 2D and the 3D is almost there. Testing seems to be going well. This, until is properly published is not getting into the main code either ;-) but eventually, it will end up there.

**Comment by fake-name** [comment]
And /that/ is why I wanted to touch-base before starting doing something. Awesome!

**Comment by craig-warren** [comment]
@fake-name we welcome assistance in improving the code! As Antonis said, we hope to release an update soon that includes the CUDA-based GPU solver we have been working on. When we do this (or perhaps beforehand) it will be useful to have people to give it a spin on their GPU.

We don't have a MPI domain decomposition at the moment, so a model can't currently be split across multiple computational nodes. This means models are limited to the RAM on a node. What type of problem are you using (or intending to use) gprMax for?

In terms on cleaning up the code, I think the worst offenders are the modules that read commands from the input file, i.e. `input_cmds_**` These were largely ported over from the previous C code to Python. There is a lot of repeated stuff that could definitely be made into functions.

We are happy to answer questions on code functionality, or reasons for particular design choices.

**Comment by fake-name** [comment]
It came from C? That makes things make a lot more sense. 

Anyways, I'm currently working on learning the general grid structure, by way of heavily restructuring the way  `input_cmds_geometery.py` works. 

The idea I have is a structure where the geometery commands are parsed into composeable geometery objects, which then install themselves into the "world" grid. This allows me to define a specific interface (albeit simple) that geometery objects must have, and it also makes it possible to construct a scene in a pure python script (since a scene can be described as a set of objects).

Anyways, I have two branches I'm poking about with: https://github.com/fake-name/gprMax/tree/master, which is mostly an attempt to get the line-lengths under some control (I shouldn't have to scroll horizontally with a 1920 * 1080 monitor), and https://github.com/fake-name/gprMax/tree/rework which is where I'm doing the more aggressive restructuring.

Should I pull request my master branch? It basically has only white-space changes.

**Comment by fake-name** [comment]
Ok, quick question. [`utilities.py`](https://github.com/gprMax/gprMax/blob/master/gprMax/utilities.py) has a [`round_number()`](https://github.com/gprMax/gprMax/blob/master/gprMax/utilities.py#L106) function. 

Is there a reason this is round-tripping through the `Decimal()` class? Python has the built-in [`round()`](https://docs.python.org/3/library/functions.html#round) function that exactly matches the method signature of the `round_value()` call. 

I can only think that either 1. the person didn't know about the `round()` builtin, or 2. There's some odd floating point issues that casting through the `Decimal()` class works around. Is it the latter, or can I replace `round_number()` with `round()` when I run into it?

**Comment by craig-warren** [comment]
Yes, please do a pull request for the whitespace changes.

The reason for the `round_value()` function was because we wanted to round halves down to keep with the behaviour of the previous C version of gprMax. The built-in `round()` AFAIK doesn't do this, e.g.
```>>>import decimal as d
>>> int(d.Decimal(1.5).quantize(d.Decimal('1'), rounding=d.ROUND_HALF_DOWN))
1
>>> round(1.5)
2
```
I want to give some explanation for the reasons for using simple commands in a input file to build models. This is what was done in the old C-version of gprMax, so firstly we wanted to maintain a degree of compatibility; secondly, many of our users don't have a lot of programming skills, to the extent that they perhaps only know a little MATLAB and thats it. So keeping a very simple method of building models with input (hash) commands for these users was important. That said, many users were building input files using scripts (mostly MATLAB), so we wanted to also offer the ability to use scripting (with Python) within the input file in the new version of gprMax - hence the `#python, #end_python` commands (a Python block). 

You may have also noticed that there is a module `input_cmd_funcs.py`, kindly written by @obtitus, which are Python functions that print the hash commands. This makes it a bit less clunky to use the hash commands within a Python block in the input file. So essentially the hash commands are first class citizens which are translated into Python functions. However, what we would like to do (and I think this would be a lot cleaner/nicer) is make the Python functions the first class citizens. So expose functions in a simple API that users can use in a Python block in the input file. The same functions can also be used to process any hash commands in the `input_cmds_singleuse.py`, `input_cmds_multiuse.py`, `input_cmds_geometry.py`. 

I hope this makes some sense and helps you understand the code (and some of our design decisions) a bit more.

**Comment by fake-name** [comment]
Ohhhhhh, it's a compatibility thing. That makes a lot more sense.

Python does round-towards-even, which I think is supposed to balance out any rounding bias, but if you're trying to maintain output matching with a codebase that doesn't do that, it makes perfect sense.

------

To be clear, I don't have an issue with the way the input files work. It's a useable minimal configuration file structure.

What I'm putting together is basically a two step process for the input file processing - The input file is processed into a list of python objects that 1:1 correspond to the lines in the file, and then those python  objects are then "installed" (bad terminology?) into the grid.

The idea being that you can create the object list any way you want, it doesn't have to be via the input file structure. That way, it'd be extremely straight-forward to write a script that creates the relevant input objects, and then calls `simulate(objects)` or similar (not a good name yet, TBD).


---

Changes are PR-ed [here](https://github.com/gprMax/gprMax/pull/108)
