### ISSUE TITLE
Bug in the #add_grass input

### ISSUE THREAD

**Issue by heazel** [gprMax/gprMax#114]
While I was trying to simulate a fractal box and get its geometry view, I found that the grass would not show up or in the command prompt I would get an error saying that the index is out bound. I know that it's not a problem from my simulation, since I simulated the example in the docs and got the same error!

I wanted the geometry view, so I used the --geometry-only flag. I attached the .in file to show that my model doesn't have erros (I think).

```
#title: Pruee
#domain: 0.2 0.2 0.2
#dx_dy_dz: 0.001 0.001 0.001
#time_window: 6e-9

#waveform: ricker 1 1.5e9 my_ricker
#hertzian_dipole: y 0.045 0.075 0.085 my_ricker
#rx: 0.105 0.075 0.185

#soil_peplinski: 0.5 0.5 2.0 2.66 0.001 0.25 my_soil
#fractal_box: 0 0 0 0.15 0.15 0.100 1.5 1 1 1 50 my_soil my_soil_box
#add_grass: 0 0 0.100 0.15 0.15 0.100 1.5 0.03 0.08 100 my_soil_box

#geometry_view: 0 0 0.06 0.15 0.15 0.2 0.001 0.001 0.001 heterogeneous_soil n

```

**Comment by craig-warren** [comment]
@heazel Can you confirm the version number of gprMax that you are using.

Thanks,
Craig

**Comment by heazel** [comment]
I'm using v3.0.20 and when I increase the upper limit of the grass height beyond 0.8, I get the following error: `IndexError: index 155 is out of bounds for axis 2 with size 155`. I attached an screenshot of the error.
![error](https://user-images.githubusercontent.com/29560978/27382999-a43e5a58-564e-11e7-94b7-0bd2ee1eeb58.PNG)

**Comment by craig-warren** [comment]
@heazel thanks for spotting this. The bug was related to building the roots for the grass (rather than the grass blades). I've corrected this in the latest release v.3.1.1 (v.3.1.0 was a big release we made on Mon which contains functionality to allow gprMax to run on GPUs).

I don't really understand why you would be specifying a height of 0.8m? Your soil_box zplus surface is at 0.1m so, the maximum range for your grass would be between 0.101 and 0.18 (allowing for the PML and some space). Obviously, you can use any range you like in between these values.

**Comment by heazel** [comment]
Yeah you're right, I meant increasing the height beyond 0.08m. My apologies.
