### ISSUE TITLE
New 400 MHz GSSI Antenna Model

### ISSUE THREAD

**Issue by mzunguman** [gprMax/gprMax#116]
Dear authors,

for my Masters thesis I implemented and worked with a model of a 400 MHz GSSI antenna in gprMax, leaning on how the pre-installed models are built. It is most likely not implemented as robustly/well as the pre-installed 1.2 GHz Mala and 1.5 GHz GSSI antenna in the model library, but if it is of interest I would be glad to contribute to the project with my antenna model. I will be happy to possibly gain some insight from other users and gradually improve the model and would try my best to add comments indicating the experimental state and general details of the model. 

Please feel free to ask me questions regarding my model and/or let me know the best way to add my model to the library.

Cheers,
Sam

**Comment by craig-warren** [comment]
@mzunguman yes, of course, we are interested in adding contributions such as yours to the user library. I'm going to restructure the `antennas.py` module and associated docs to better allow the addition of other antennas. Meantime can you email me (Craig.Warren@ed.ac.uk): details of the antenna model; how it was constructed and validated; whether you are happy to use the same Creative Commons Attribution-ShareAlike 4.0 International License, and what attribution you'd like.

Kind regards,
Craig

**Comment by captainKobo** [comment]
I was curious as to how I might obtain a copy of the code for the 400 MHz GSSI antenna.  I am retired EE (wireless background) who is helping my daughter do gprMax simulations (excellent simulation tool that you have put in place Craig).  She is a graduate student at Texas A&M University in soil sciences and she is using a pulseEKKO PRO GPR at 500 MHz in attempt to detect sorghum and cowpea roots.  I have run extensive simulations for her using the Hertzian dipole at 500 MHz and just recently using the MALA 1200.  The latter gave much better results and I was looking into modifying it for 500 MHz, but that appears quite daunting.  When I saw this chain I was quite excited since this is very close to what I'm looking for.  Sam I applaud your efforts in developing this antenna and I completely understand that your model is probably not as accurate as Craig's model of the MALA 1200, but all I'm looking for is a feel for how this might work at the lower frequency.  If you could send me the code directly that would be great or if that has to go through Craig, either way.  My very recent version of gprMax does not have this 400 MHz antenna in user_libs.  Thanks.  My contact information is as follows:
Rich Kobylinski
rkoby@swbell.net

**Comment by craig-warren** [comment]
@captainKobo as you can see I had some discussions with @mzunguman a few months ago. Sam is happy for his 400MHz antenna model to be part of the user libraries with a CC license. My plan was to do a bit of re-organising of the antennas module and include Sam's model along with documentation on how it was created and verified. I just haven't had time to do this yet! I am hoping to get around to it in the next 4 weeks. If you want it sooner you may be better getting the model directly from Sam if you can.

**Comment by mzunguman** [comment]
Thank you @captainKobo for the interest, I'm glad someone else is interested in my work. What @craig-warren said makes sense if you have the time to wait until he has the time to reorganize the antenna library etc. Otherwise I'd be happy to share the code with you beforehand if you want, in that case you can write me an email at stadler.sam@gmail.com.

**Comment by captainKobo** [comment]
Thank you both for your quick responses.  I look forward to Craig updating the antennas module in a future version of grpMax, and Sam I am going to send you a separate email requesting the code before that.  As I said in my comment, I want to get a feel for how performance will be effected using this lower frequency.  Thanks again.

**Comment by craig-warren** [comment]
@captainKobo this antenna is now part of the gprMax user_libraries package. Thanks to @mzunguman for sharing his work.
