### ISSUE TITLE
Dispersion analysis problem with large number of time steps

### ISSUE THREAD

**Issue by berndschafferer** [gprMax/gprMax#121]
Hi, 

I encountered a problem when generating a geometry file for down scaled model. Below are 2 input files. The first is working fine and will generate the .vti file.
The second one will not finish.   
The command for generating the model was api(fni, n=1, geometry_only=True)
below is the log output for the second input file. The writing of the .vti will not start.   
Thanks, 
Bernd

-------------------------------------------------------------------------------------------------------------------------------
WORKING
#dx_dy_dz:  0.0001  0.0001  0.0001 
#domain:   0.02   0.02   0.01 
#time_window: 1e-08 
#waveform: gaussian 1 2.4e9 mypulse 
#material: 1 1e-05 1 0 resmat 
#box: 0.005 0.005 0.005 0.01 0.01 0.0051 pec 
#geometry_view: 0 0 0  0.02 0.02 0.01 0.0001 0.0001 0.0001 gprmax_trl n 

-------------------------------------------------------------------------------------------------------------------------------

NOT WORKING:
#dx_dy_dz:   1e-05   1e-05   1e-05 
#domain:  0.002  0.002  0.001 
#time_window: 1e-08 
#waveform: gaussian 1 2.4e9 mypulse 
#material: 1 1e-05 1 0 resmat 
#box: 0.0005 0.0005 0.0005 0.001 0.001 0.00051 pec 
#geometry_view: 0 0 0  0.002 0.002 0.001 1e-05 1e-05 1e-05 gprmax_trl n 

-------------------------------------------------------------------------------------------------------------------------------

LOG FOR THE SECOND FILE 
=== Electromagnetic modelling software based on the Finite-Difference Time-Domain (FDTD) method 

    www.gprmax.com   __  __
     __ _ _ __  _ __|  \/  | __ ___  __
    / _` | '_ \| '__| |\/| |/ _` \ \/ /
   | (_| | |_) | |  | |  | | (_| |>  <
    \__, | .__/|_|  |_|  |_|\__,_/_/\_\
    |___/|_|
                     v3.1.1 (Big Smoke)

 Copyright (C) 2015-2017: The University of Edinburgh
 Authors: Craig Warren and Antonis Giannopoulos

 gprMax is free software: you can redistribute it and/or modify it under the
  terms of the GNU General Public License as published by the Free Software
  Foundation, either version 3 of the License, or (at your option) any later
  version.
 gprMax is distributed in the hope that it will be useful, but WITHOUT ANY
  WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR
  A PARTICULAR PURPOSE.  See the GNU General Public License for more details.
 You should have received a copy of the GNU General Public License along with
  gprMax.  If not, see www.gnu.org/licenses.

Host: Dell Inc. Studio XPS 435MT; 1 x Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz (4 cores, 8 cores with Hyper-Threading); 7.79GiB RAM; Linux (3.13.0-128-generic, debian)

--- Model 1/1, input file: gprmax_trl.in --------------------------------------

Constants/variables used/available for Python scripting: {c: 299792458.0, current_model_run: 1, e0: 8.854187817620389e-12, inputfile: /home/bernd/gprMax/tools/Jupyter notebooks/termination/gprmax_trl.in, m0: 1.2566370614359173e-06, number_model_runs: 1, z0: 376.73031346177066}

Number of CPU (OpenMP) threads: 4
Spatial discretisation: 1e-05 x 1e-05 x 1e-05m
Domain size: 0.002 x 0.002 x 0.001m (200 x 200 x 100 = 4e+06 cells)
Estimated memory (RAM) required: ~340MB
Time step (at 3D CFL limit): 1.92583e-14 secs
Time window: 1e-08 secs (519257 iterations)

Waveform mypulse of type gaussian with maximum amplitude scaling 1, frequency 2.4e+09Hz created.
Material resmat with eps_r=1, sigma=1e-05 S/m; mu_r=1, sigma*=0 Ohm/m created.
Geometry view from 0m, 0m, 0m, to 0.002m, 0.002m, 0.001m, discretisation 1e-05m, 1e-05m, 1e-05m, with filename base gprmax_trl created.
Box from 0.0005m, 0.0005m, 0.0005m, to 0.001m, 0.001m, 0.00051m of material(s) pec created, dielectric smoothing is off.
Processing geometry related cmds: 100%|████████| 1/1 [00:00<00:00, 25.23cmds/s]

PML boundaries: 10 cells
Building PML boundaries: 100%|███████████████████| 6/6 [00:01<00:00,  3.25it/s]

Building main grid: 100%|████████████████████████| 2/2 [00:00<00:00,  4.49it/s]

Materials:
    |            |         |       | sigma |      | sigma*  | Dielectric 
 ID | Name       | Type    | eps_r | [S/m] | mu_r | [Ohm/m] | smoothable 
----+------------+---------+-------+-------+------+---------+------------
  0 | pec        | builtin | 1     | inf   | 1    | 0       | False      
  1 | free_space | builtin | 1     | 0     | 1    | 0       | True       
  2 | resmat     |         | 1     | 1e-05 | 1    | 0       | True

**Comment by jasminium** [comment]
Hello.

I just ran the not working example and it hangs for me at 
grid.py line 253
power = 10 * np.log10(np.abs(np.fft.fft(waveformvalues))**2)

The excitation has a lot a values due to the very fine mesh size in the model. Which is presumably why the fft is hanging. I wonder if we should have an option to disable dispersion analysis for very fine meshes @craig-warren?

**Comment by craig-warren** [comment]
@berndschafferer @jasminium Yes, it is an issue with the dispersion analysis and the number of time steps (~52000) in the model, because of the time window and spatial discretisation used. I don't think disabling the dispersion analysis is necessarily the right thing to do, but we may need to find a better way to analyse the maximum frequency content in a waveform when there are a large number of time steps.  Perhaps: 

* doing something to only analyse the part where the source waveform is active, and/or
* using a decimate function, or 
* for large number of time steps using an estimation of maximum frequency of interest that is simply a multiple of the centre frequency of the pulse (this is probably easiest)

Thoughts?

**Comment by agianno** [comment]
@craig-warren @jasminium For theoretical waveforms that are standard in gprMax we do not need to use FFTs as we can mathematically obtain the spectrum and find the frequency for a given power level needed. For user-specified waveforms that obviously is not possible. If we want to use FFTs because they are simple then we can set the source function that is used in the velocity analysis to be sampled not up to the time window specified by the user but to a predetermined time window that makes sense for analysing the specific waveform. For example, we can set this to be 5 pulse widths or around there. The only difference would be the frequency resolution of the plot but that should not matter too much.

**Comment by berndschafferer** [comment]
not sure if this is on topic, but 
power = 10 * np.log10(np.abs(np.fft.fft(waveformvalues))**2)
holds always the potential of disaster 
we usually use a stopper value for the log .
power = 10 * np.log10(1e-10 + np.abs(np.fft.fft(waveformvalues))**2)

**Comment by craig-warren** [comment]
I adjusted the dispersion analysis function to perform the FFT over 4 times the pulse width for builtin waveforms.
