### ISSUE TITLE
Could we develop new module to build up geometric units? 

### ISSUE THREAD

**Issue by zhoufeng617** [gprMax/gprMax#133]
gprMax has a limited number of commands to build up a variety of geometric objects. For some specific geometrci objects that can not be directly created with the present commands, we can indirectly synthesize them with the existing commands. For example, a circular cylinder can be made by overlapping two cylinders with different radii. However, building two cylinders might consume much time because all the cells within the outer circulars should be assigned, whereas the inner circular is actually useless. I was wondering if it is possible to develop a new command to directly build up a circular cylinder without overlapped cylinder command. I am working with gprMax in a borehole fluidal environment, where the radially changing fluid saturations can be modelled as a series of circular cylinders.  I found a lot time is spent in building each cylinder for a circular cylinder creating. If a circular cylinder command is directly availbale, the running time can be decreased dramatically. How do you think about it?

**Comment by craig-warren** [comment]
@zhoufeng617 the design behind the geometry building of gprMax is that there a few primitives that can be used for simple geometries, and users can then use Python scripting to build their own more complex objects. We also have the possibility to save geometry (with #geometry_objects_write) to file, so that if you need to re-use it, say for a B-scan, then you can more quickly read the geometry from file (with #geometry_objects_read) so you don't have to build the geometry for every run. This may help in your case, if your geometry is the same for different runs.

We have no specific plans at present to add further geometry objects. Our next focus on the geometry building side of the software will be to look at creating a converter so that a standard CAD format file can be converted into a FDTD mesh. However, this is not a trivial process.
