### ISSUE TITLE
How does the convert_png2h5.py module work?

### ISSUE THREAD

**Issue by Angelisd** [gprMax/gprMax#142]
Hello!
Yesterday I was testing the convert_png tool to create some models and I found out that there is a possible bug regarding the pixels of the png image.

The model that I want to construct is 9x2.1x0.005, so to do that I created a png image with 900x210 pixels (Fig.1).
However, when i run the geometry_view the result is 4.5x1.05x0.005 (Fig.2). I can double the pixels to create my model, but I just wanted to inform you about this issue.

Kind Regards,
Dimitris

![fig1](https://user-images.githubusercontent.com/37277513/37259639-8b537984-2591-11e8-91c5-7f70eed496f2.png)

![fig2](https://user-images.githubusercontent.com/37277513/37259644-9c1f44f0-2591-11e8-84d8-994030191813.png)

**Comment by craig-warren** [comment]
@Angelisd can you attach the png and input files you are using that produce these results. Thanks.

**Comment by Angelisd** [comment]
Hello Craig!
The files that you have requested.

[Desktop.zip](https://github.com/gprMax/gprMax/files/1802426/Desktop.zip)

**Comment by craig-warren** [comment]
@Angelisd from your input file your domain is `#domain: 9 2.1 0.005` with `#dx_dy_dz: 0.005 0.005 0.005` giving number of cells 1800 x 420 x 1. Therefore you would need an image with these pixel dimensions to fill the domain. Your image is 900 x 210 which is why it looks as it does.

Each pixel in the PNG image should correspond to a cell in the model. I threw the `convert_png2h5.py` module together quickly, so feel free to suggest changes and improvements.

**Comment by Angelisd** [comment]
Ok, I understand now :)
Thank you for your answer.
