### ISSUE TITLE
Sinusoidale surface

### ISSUE THREAD

**Issue by ELEGER** [gprMax/gprMax#18]
Hi again,
coming back with the same problem I cannot figure out why I cannot see any reflection and anything in the vti file.
I'm fine on Time window as well as on geometry.
I'd be glad to understand why I cannot see anything on the vti and ultimately on my radargram. Cheers
[fractal.txt](https://github.com/gprMax/gprMax/files/71478/fractal.txt)

**Comment by craig-warren** [comment]
You are not building any boxes because you haven't separated the `#box:` commands from the first coordinates with a space, e.g. you have `#box:0.000 1.495 ...` you require `#box: 0.000 1.495 ...` 

Also the step size you are using for the sources and receivers is 1 metre therefore you'll only get 2 traces in your radargram.

**Comment by ELEGER** [comment]
Very good Craig, the issue was the space... stupid of me..
Yes I knew about the number of traces thank you though
Thanks for your quick answer

best
e
