### ISSUE TITLE
Results error in different computer

### ISSUE THREAD

**Issue by zhoufeng617** [gprMax/gprMax#205]
I have some gprMax files. I run them well in my laptop. I run it in the tower work station, it seems every is ok. But when I plot the .out file with MATLAB tool, there is an error like below. I do not understand why it is like this. I tried times and it is still like this.   

"In C_plot_Ascan (line 16) 
Error using hdf5lib2
The HDF5 library encountered an error and produced the following stack trace information:

    H5O_attr_open_by_name    can't locate attribute: 'dx_dy_dz'
    H5A_open_by_name         unable to load attribute info from object header
    H5Aopen_name             can't open attribute: 'dx_dy_dz'

Error in H5A.open_name (line 16)
attr_id = H5ML.hdf5lib2('H5Aopen_name', loc_id,name);

Error in h5readatt (line 48)
attr_id = H5A.open_name(obj_id,options.Attname);

Error in C_plot_Ascan (line 20)
    tmp = h5readatt(fullfilename, '/', 'dx_dy_dz'); "

**Comment by craig-warren** [comment]
@zhoufeng617 I suspect this is because you are trying to load an older model, or that the versions of gprMax on the different computers are not the same. We changed the name of this particular attribute in the output file in July 2018 (https://github.com/gprMax/gprMax/commit/a1512086bc2a4eaaa363f54bfdb784c37689f7a9#diff-e501e05d3adf92c05f917a53ff68e73f). So you can either re-run your model with the new code, or if it has a long runtime, then just edit the HDF5 file and change the name of the attribute.

Kind regards,

Craig
