### ISSUE TITLE
memory_check() function considers total ram and not total virtual memory free

### ISSUE THREAD

**Issue by spaceVStab** [gprMax/gprMax#209]
The `memory_check()` function is considering the total ram of the system while evaluating if host can run the simulations with estimated memory usage.

Rather the virtual memory free at that instant must be considered.

`psutil.virtual_memory().available` gives the virtual memory available at that instant.

https://github.com/gprMax/gprMax/blob/142b9b40641226a2244c43e0e728d5e2b7fb8bbf/gprMax/grid.py#L235

**Comment by craig-warren** [comment]
@spaceVStab interesting point. The idea of looking at the total RAM of the machine was always with the idea of 'what is the largest model I can run if all memory is free'. However, I take your point, and tend to agree that it makes more sense to consider the virtual memory free at that instant. @agianno any thoughts?

**Comment by agianno** [comment]
For determining available memory it is obviously correct as from the total hardware available memory there is memory that the OS will take as well any other apps etc. currently running. I think reporting both is a good idea. People might think that if the system has 32Gb then that is what the maximum they can run with is which is obviously not right. So, reporting both system Max and currently available it is right. Obviously, system max memory is something the user should know already but the problem here is to prevent people thinking that "we do not see" the complete available memory for some reason … If we report this they will know that we do but the available memory to them at this stage is different.

A

**Comment by spaceVStab** [comment]
Yes, reporting both memory is a good idea. Should I raise a PR with first version of opencl solver?

 I shall also see if further improvements on memory reporting and management can be made and let you know.

**Comment by craig-warren** [comment]
@spaceVStab I think a new branch for the OpenCL solver might be the best idea.

**Comment by spaceVStab** [comment]
Yes, Sure. I guess I will have to submit a PR in new branch (opencl-dev). That should work.
