### ISSUE TITLE
Bscan does not move voltage source

### ISSUE THREAD

**Issue by GaleonAD** [gprMax/gprMax#251]
I've changed #hertzian_dipole to #voltage_source in example with cylinder. Location of #voltage_source not change during Bscan (checked in separate files the location of srcs/src1)

**Comment by craig-warren** [comment]
@GaleonAD yes, this is designed/expected behaviour. The `#voltage_source` is meant to be used with an antenna model, i.e. one that has some structure. Conversely, the `#hertzian_dipole` and `#magnetic_dipole` are classed as simple source models, representing for example an infinitesimal electric dipole in the case of the `#hertzian_dipole`. Only the simple sources can be moved with the `#src_steps` command. If you want to move other sources, and indeed pieces of geometry etc..., then you can do so using the `#python` blocks and some scripting, see the example of the moving the antenna model in the docs - http://docs.gprmax.com/en/latest/examples_antennas.html#b-scan-with-a-bowtie-antenna-model

**Comment by GaleonAD** [comment]
@craig-warren Thak you for clarification.
