### ISSUE TITLE
Problem with geometry view

### ISSUE THREAD

**Issue by JazminFerre** [gprMax/gprMax#255]
Dear Craig
I have two differents problems when i try to open files in ParaView.
If i run the code with this line 
`#geometry_view: 0 0 0 0.051 0.126 0.026 0.001 0.001 0.001 pml_3D_pec_plate_f f`
I have the following error
![WhatsApp Image 2020-05-27 at 4 18 52 PM](https://user-images.githubusercontent.com/31524099/83063094-01f91280-a036-11ea-89ae-6d079426c1ca.jpeg)

If I change the line to this
`#geometry_view: 0 0 0 0.051 0.126 0.026 0.001 0.001 0.001 pml_3D_pec_plate_n n`
I have this problem when i try to open the PEC material
![WhatsApp Image 2020-05-27 at 4 19 48 PM](https://user-images.githubusercontent.com/31524099/83063262-38cf2880-a036-11ea-9aa2-209bc4dc3805.jpeg)
ParaView is 5.8.0, GprMax version is the last I downloaded it a few days ago and i'm running it in Windows 10.
Do you have an idea of what is happening?  

Thanks you!
Best regards,
Jazmin

**Comment by craig-warren** [comment]
@JazminFerre the second ‘error’ is actually just a warning from Paraview, and indicates that it couldn’t find any cells with the material PEC in your model. Probably because your PEC objects are plates or edges that don’t occupy an entire Yee cell. So this behaviour is expected. 

The first error with the .vtp file I have not seen before and will need to look into. Can you attach the actual .vtp file please. I may need you to do some tests as I don’t currently have access to a Windows 10 machine.

**Comment by JazminFerre** [comment]
Thanks!! I didnt understand what the warning mean, now i do.
I send you the file.
[pml_3D_pec_plate_f.txt](https://github.com/gprMax/gprMax/files/4691458/pml_3D_pec_plate_f.txt)

Thanks again.

**Comment by craig-warren** [comment]
@JazminFerre this seems to be something to do with newer versions of Paraview. I have v5.5.2 and the .vtp file opens OK. Until I get more time to look into it, I recommend installing an older version of Paraview.

**Comment by JazminFerre** [comment]
It works!!
Thanks a lot!
I will keep working with version 5.5.2!
Thanks again!

**Comment by craig-warren** [comment]
@JazminFerre definitely looks like this is a bug with Paraview 5.8 - https://gitlab.kitware.com/paraview/paraview/issues/19698#note_713063

I am going to close this issue as it should be fixed in Paraview 5.8.1.
