### ISSUE TITLE
Possible Formula Error for Debye Model

### ISSUE THREAD

**Issue by GGDRriedel** [gprMax/gprMax#262]
https://github.com/gprMax/gprMax/blob/73a3f93a086b3a8ec5230d241d1716f11b6b92ce/gprMax/materials.py#L303

Referencing the Peplinski paper in http://dx.doi.org/10.1109/36.387598 

Formula (2), there is a possible error in the  FCode, as there is a -1 too much

Code says 
```
er = (1 + (self.rb / self.rs) * ((es**a) - 1) + (muiter[0]**b1 * erealw**a) - muiter[0]) ** (1 / a)
```

when according to paper it should be 
```
er = (1 + (self.rb / self.rs) * (es**a)  + (muiter[0]**b1 * erealw**a) - muiter[0]) ** (1 / a)
```

**Comment by agianno** [comment]
There is no error although you do raise a valid point to clarify. The formula is actually based on the original 1985 paper by Dobson et al. (Equation (28)) that Peplinski has worked upon to extent its frequency range of validity (Dobson et. al. IEEE TGRS, 1985, issue 1 or Paper [1] in Peplinski's paper).  The next formula in the code is the adjustment for bringing the Dobson's model's validity to the 0.3  - 1.3 GHz range which is what Peplinski introduced.  (Why we call it Peplinski's?) Now there is a good question why Peplinksi's equation (2) in the 1995 paper is missing this extra "1". But I think what the work which introduced this has checked that produces reasonable results. For information on the model as used in the old version of gprMax and then incorporate into the current version please see Dr Giannakis's thesis https://era.ed.ac.uk/handle/1842/20449

**Comment by GGDRriedel** [comment]
So that means that either there is a typo that nobody caught since 1995 in a peer-reviewed article or I am looking at a weird version of it. (Formula 4.87)
The doctors thesis you linked also quotes Peplinski and quotes the correct formula so what is going on here?

**Comment by craig-warren** [comment]
@GGDRriedel just to reinforce what @agianno said:

[Dobson (1985)](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=4072240) equation 28 and [Peplinski (1995)](https://ieeexplore.ieee.org/stamp/stamp.jsp?tp=&arnumber=387598) equation 2 differ. This is the equation for the real part of the soil model that is valid in the region 1.4-18GHz. It is Dobson's equation that is used both in [Dr Giannakis's PhD thesis](https://era.ed.ac.uk/handle/1842/20449) equation 4.87 and in the [gprMax materials module code](https://github.com/gprMax/gprMax/blob/73a3f93a086b3a8ec5230d241d1716f11b6b92ce/gprMax/materials.py#L303). We believe this is the correct version and that there is an error in the Peplinski paper.

The secondary matter is whether the model should be called Dobson's rather than Peplinski's since he was the original author. This is something we will consider.
