### ISSUE TITLE
What are the built-in electromagnetic parameters of "pec" ?

### ISSUE THREAD

**Issue by hhrm** [gprMax/gprMax#275]
What are the built-in electromagnetic parameters of "pec" ?

**Comment by agianno** [comment]
PEC is enforced as a boundary condition (electric field is equal to zero) and no medium parameters are used. In order to keep the material class "happy" parameters for permittivity and conductivity might be there for PEC but they are not used in update equations. In a PEC the electric field is zero and there is no penetration (i.e. skin depth) as conductivity should be infinite.

**Comment by hhrm** [comment]
So what parameters can I use to simulate the surface of metal by myself, such as the permittivity?

**Comment by agianno** [comment]
You can create any material type you like and details are given in the manual. The properties can be frequency dependent or not and metals can be modelled that way if needed. If you need to model skin depth penetration etc. you need to have enough spatial resolution and the right properties. The theoretical framework and implementation in gprMax allows you to do this. How and why and what properties to use is up to you and depends on the problem you are trying to simulate. There is a lot of information in the literature. PEC is universally treaded as a boundary condition as in a "perfect" conductor conductivity is infinite and skin depth is zero and hence the electric field is zero. In many cases this is a very good and easy approximation of metal structures and is used in many methods and not only in FDTD. If you use PEC there are no "properties " to set. Hope this is more clear.
