### ISSUE TITLE
GPU execution error when include material randomly generated

### ISSUE THREAD

**Issue by Johnson0127** [gprMax/gprMax#299]
Thanks for the great job about gprmax!

I have used gprmax3 with miniconda3 and the GPU mode have succeeded working after cuda and pycuda installed for some cases simulation( example code works fine).

However, what I am doing is to input more complex environment i.e. random medium (likely about 40000 kinds of material which generated randomly with mean value and variance) into .in file with #include file and # box function.

When I run the code with -gpu option, it comes the following message

pycuda.driver.CompileError: nvcc compilation of C:\Users\Johnson\AppData\Local\Temp\tmpvq8w9bqy\kernel.cu failed
[command: nvcc --cubin -w -arch sm_75 -m64 -Ic:\users\johnson\anaconda3\envs\gprmax\lib\site-packages\pycuda\cuda kernel.cu]
[stdout:
ptxas error   : File uses too much global constant data (0x186a78 bytes, 0x10000 max)
kernel.cu
]

the ncvv version that I use is listed as below:

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Jan_28_19:41:49_Pacific_Standard_Time_2021
Cuda compilation tools, release 11.2, V11.2.142
Build cuda_11.2.r11.2/compiler.29558016_0

Now, I could use normal option with cpu to run the cases, but it is inefficient because of different excuation time( almost 17 times difference).

I'm appreciated if you have any idea that I can use the option -gpu to run this kind of simulation.

**Comment by craig-warren** [comment]
@Johnson0127 the crux of the error is `ptxas error : File uses too much global constant data (0x186a78 bytes, 0x10000 max)`, i.e. your have too many materials for the global constant memory area of the GPU, which is quite small compared to the GPU main memory. There is not a lot you can do about this at the moment as gprMax uses this area of memory in the GPU to store material properties since it is fast and efficient.

You might ask yourself if you **really** need ~40,000 different materials? If this is a GPR problem, could a real GPR system differentiate between different materials if they have similar properties? I'm guessing all this as I don't know your specific problem.
