### ISSUE TITLE
slow with sensor array 

### ISSUE THREAD

**Issue by cyanzhao42** [gprMax/gprMax#328]
Hi, thanks for the continuous support. I place the sensor array all over the computational domain (63*63) in my simulation. It significantly lowered the simulation speed, compared to when I only had one sensor. I think the bottleneck may be the writing part. Are there ways that I can speed this up?  Thanks!

**Comment by craig-warren** [comment]
@cyanzhao42 yes, adding a lot of field outputs points (receivers, #rx command) will inevitably slow down the simulation, as the solver must store (in memory) the time history of the fields at each output point. There is no getting around this! No file writing takes place until the each of the simulation so the speed reduction is just due to writing to memory. What you can consider to improve speed is only output the field component, i.e. Ex, Ey, Ez, Hx, Hy, Hz, that you require. You can do this by looking at the syntax of the receiver command (https://docs.gprmax.com/en/latest/input.html#rx) and the optional parameters `str1` and `str2`.

**Comment by cyanzhao42** [comment]
Thanks for the note! I am trying to incorporate `str1` and `str2` as you mentioned. However, it seems that it only supports `rx` and is not supported for `rx_array`. Do you know how I can specify `str1` and `str2`  for  `rx_array`? Thanks!

**Comment by cyanzhao42** [comment]
resolved, I just add all sensors via `rx `
