### ISSUE TITLE
Error examples/Subgrids/gssi 

### ISSUE THREAD

**Issue by GGDRriedel** [gprMax/gprMax#385]
V4 , can't tag for some reason
Error mesage:

```
(gprMax-devel) riedel@AMD-Server01:/media/raid0/Riedel/gprmaxv4/gprMax$ python examples/subgrids/gssi_400_over_fractal_subsurface.py 
<gprMax.cmds_singleuse.ExcitationFile object at 0x7fe1c79d55d0> this Object can not be added to a sub grid
NoneType: None
Traceback (most recent call last):
  File "/media/raid0/Riedel/gprmaxv4/gprMax/examples/subgrids/gssi_400_over_fractal_subsurface.py", line 110, in <module>
    sg.add(obj)
  File "/media/raid0/Riedel/gprmaxv4/gprMax/gprMax/subgrids/user_objects.py", line 49, in add
    raise ValueError
ValueError
```

calling method 

```
python examples/subgrids/gssi_400_over_fractal_subsurface.py```

**Comment by GGDRriedel** [comment]
The problem is that the exitation object is not within the add function in

user_objects.py  


the logic in it doesn't allow for exitation objects

**Comment by craig-warren** [comment]
@GGDRriedel, thanks this has cropped up because the GSSI 400MHz antenna model has recently moved to using a user-defined waveform (via ExcitationFile) which wasn't previously allowed within a subgrid. There is no good reason that ExcitationFile cannot be used (multiple times if required) within a subgrid, so I will look into correcting this.

**Comment by craig-warren** [comment]
@GGDRriedel should now be fixed in the latest changes - excitation file can now be used multiple times.
