### ISSUE TITLE
B-scan with n traces

### ISSUE THREAD

**Issue by GHozzi** [gprMax/gprMax#43]
Hi, 
I would like to ask about B-Scan. For example, To run the model for a B-scan with 60 traces:
python -m gprMax cylinder_Bscan_2D.in -n 60

But, when the running program is interrupted in the 25 traces. Is there some  command  for running the B-scan starting with 25th trace, rather  than repeating the simulation  and  going back to the beginning.

Thank you in advance for your answer.

**Comment by craig-warren** [comment]
@GHozzi there is not currently an automatic mechanism for re-starting a simulation is it was interrupted. However, because a B-scan is saved as a series of A-scans (before merging) you can manually move your source/antenna to where it would have been on the 25th trace and start a new simulation from there. Just be careful of the numbering when combining the A-scans together.

**Comment by GHozzi** [comment]
Thanks @craig-warren for your answer. I will try to do it.
