### ISSUE TITLE
Multiple Receiver positions

### ISSUE THREAD

**Issue by ELEGER** [gprMax/gprMax#60]
Hi Craig,
I have a question concerning a profile of receivers, namely just one source and an array of receivers only in one direction.

Can I use the function #rx_box, or should I do a #rx_step?

In:
#rx_box: f1 f2 f3 f4 f5 f6 f7 f8 f9, 

f7 f8 and f9 need to be at least superior or equal than the deltas, so If I want to have something like:

#rx_box: X1 Y1 Z1 X2 Y2 Z2 dX1 0.000000 0.000000

with the constrain Y1==Y2, and Z1==Z2,

Is it possible or I have to do multiple Rx_steps?

Thanks in advance

e.

**Comment by agianno** [comment]
I think you should be able to use the #rx_box: the way you want to. If not we should change this to be able to have just a line and not only a box. At the moment if it does not work use a box with one step size in the two directions (you get a few more receivers) but you can discard them. 

Alternative use a simple python scripting with an #python: #end_python block to generate the #rx: positions you want. The #rx_steps: command is only useful if you are re-running the mode and you want to move the receiver positions. It could work but you will be wasting computation time as you will be running a new model for the same source in order to get a new receiver position.

Best

Antonis

**Comment by ELEGER** [comment]
Hi Antonis,
Thanks for your quick reply.
Can't use the #rx_box without settings dx,dy,dz different from zero.


So I can write multiple #rx: with a python blocks? that should be the most efficient writting in term of computation.


Thanks

emmanuel

**Comment by craig-warren** [comment]
You should be able to do lines with ``#rx_box`` command now. Note, I have renamed it ``#rx_array`` to reflect the fact it an do lines or 2D grids of receivers.

**Comment by ELEGER** [comment]
Thank you Craig.
