### ISSUE TITLE
Problem with #geometry_objects_read for 2D geometries

### ISSUE THREAD

**Issue by nallroggen** [gprMax/gprMax#92]
Hi Craig,
I found a problem (version 3.0.16) when using 2D pre-defined geometries with  #geometry_objects_read. 
As the geometry file has a dimension of one in one direction, in function "build_voxels_from_array()", the for loops over the dimensions are not executed (line 702 - 708, file: geometry_primitives.pyx).  
I suggest to check before for a one dimensional direction and make sure that the for loop is executed at least ones, e.g., by including:  
    if xs == xf:
        xf += 1
    if ys == yf:
        xf += 1
    if zs == zf:
        xf += 1
Best
Niklas A.

**Comment by craig-warren** [comment]
@nallroggen Hi Niklas,

Can I just check, is this from importing your own geometry that was not originally created by gprMax, i.e. through the `#geometry_objects_write` command?

**Comment by nallroggen** [comment]
Hi Craig, 

this is not the case for geometries written by #geometry_objects_write objects as function build_voxels_from_array() is not called for this kind of geometries. See file: 
 input_cmds_geometry.py, line 105-124

However your comment made me feel unsave as the 'geometry_objects_write', geometries have 2 field in the dimensions which in me view should only have 1 field, but that second field is zero everywhere.

Best
Niklas

**Comment by craig-warren** [comment]
@nallroggen Yeh, I guessed you were importing your own geometry and not using `#geometry_objects_write`. At the moment, internally, we allocate one extra cell in every dimension than the grid size. You can see this in grid.py line 127 when the `solid` array is allocated that stores geometry information at a voxel level. I am just checking whether we need these extra cells, because if not it makes more sense not to have them to simplify importing geometry the way you are.

I will have a look today and let you know.

**Comment by nallroggen** [comment]
Alright, I missed that! Thank you very much for the quick response! Great work you are doing! Just let me know if I can help anywhere....

**Comment by craig-warren** [comment]
@nallroggen This issue should have now disappeared in the latest code (v.3.0.17), as I've changed the internal array sizes. The result is when you import your own geometry using `#geometry_objects_read` the size of your geometry does not need to exceed the size of the model grid. I hope this makes sense.

Let me know if you have any further problems.
